### ISSUE TITLE
No README, LICENSE

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/LSSLike#1]
We need a README for this project! It should say what the projects goals are, who is working on it, and how the ideas and code in this repository should be cited. We should provide a license, too - there's a good template for LSST DESC projects [here](https://github.com/LSSTDESC/desc_package_template/blob/issue/2/copyright/%7B%7Bcookiecutter.repo_name%7D%7D/LICENSE).

**Comment by damonge** [comment]
README added (will wait for the rest when we have a clear idea, this repo is basically inexistent!)

**Comment by drphilmarshall** [comment]
Good good, thanks! :-) Did I understand from the emails that part of the
purpose is to exercise the CCL? It might be good to note that in the README
too, as well as any other ideas you are pursuing, such as which framework,
if any, you plan to make use of. Is this a project that would benefit from
CosmoSIS? Or will it sit outside CosmoSIS, on purpose? I'm just thinking of
what we could write that would help the rest of the collaboration (and in
particular the CI group) understand what this project is about. Having said
that, I guess you'll start writing a Note pretty soon after this gets
going, so I agree it's good to keep the README short!

**Comment by slosar** [comment]
LICENSE added.
